name: Hello World Demo

on:
  push:
    branches:
      - master

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Hello, GitHub Actions!"
